db:
  environment:
    MYSQL_ROOT_PASSWORD: ${DBPASSWORD}
  image: mariadb
wordpress:
  ports:
  - 80/tcp
  environment:
    LETSENCRYPT_EMAIL: ${EMAIL}
    LETSENCRYPT_HOST: ${VHOST}
    VIRTUAL_HOST: ${VHOST}
    VIRTUAL_PORT: '80'
  image: wordpress
  links:
  - db:mysql
